### ISSUE TITLE
[Bug] 窗口标题错误

### ISSUE THREAD

**Issue by alovelydoge** [Alan-CRL/IDT#24]
如图：
![屏幕截图 2024-07-04 171709](https://github.com/Alan-CRL/IDT/assets/156295679/d2522001-cd48-4ebb-83f0-08950d6586b7)
设置的窗口标题不对

**Comment by Alan-CRL** [comment]
有道理

**Comment by Alan-CRL** [comment]
这个问题已经修复，并将在下个 Beta/LTS 版本中得到
