### ISSUE TITLE
[功能请求]更优化的交互建议

### ISSUE THREAD

**Issue by alovelydoge** [Alan-CRL/IDT#25]
**1.建议增加安装包**
可以安装包和自解压 2个版本并行
安装包形式的话可以考虑添加MSI格式，方便学校使用管理软件批量部署（这个可以作为将来的计划）

**2.建议添加退出方式**
建议添加一个退出方式，比如主图标上右键弹出菜单，菜单中有选项可以彻底退出

**Comment by Alan-CRL** [comment]
对于1：目前不考虑
对于2：请打开“右键主图标提示关闭程序”选项，即可右键主图标退出程序
