### ISSUE TITLE
在多显卡模式下无法运行的bug

### ISSUE THREAD

**Issue by Liunian2000** [Alan-CRL/IDT#33]
环境Win11专业工作站22H2，是拯救者y7000p4060版本，gpu0是核显，gpu1是4060，混合显卡输出情况下完全无法运行，禁用核显后启用独显直连模式可正常使用。
希望添加一下多卡适配

**Comment by Alan-CRL** [comment]
您好，我这边需要您智绘教的版本号，以及混合输出模式下无法运行的报错截图或者现象（如无提示闪退）。

**Comment by Liunian2000** [comment]
智绘教20240719a，无提示闪退，无软件界面，任务管理器可看到短暂的出现进程，1秒内结束

**Comment by Alan-CRL** [comment]
非常抱歉，我需要更加详细的信息。请加我QQ`2685549821`，我需要您提供程序根目录下的 log 文件夹中内容，以及软件崩溃时的系统日志（事件查看器中智绘教错误事件页面的截图），谢谢。

**Comment by Alan-CRL** [comment]
此问题已经解决，需要将 `智绘教20240719a.exe` 中的非英文字符删去后即可避免此问题。
