### ISSUE TITLE
书写无法正常工作 在远程桌面触屏模式

### ISSUE THREAD

**Issue by FuziharaYukina** [Alan-CRL/IDT#8]
在使用远程桌面软件(Microsoft Remote Desktop)时。
指针模式下可以正常书写。
但是，触屏模式下滑动只可以看到点状指针（非穿透模式），但无法留下书写痕迹。
同样条件下，最新的希沃(Seewo)白板的全屏书写模式可以工作。

远程桌面使用设备：iPad Air 2
智绘教版本：Ver2402.1

**Comment by Alan-CRL** [comment]
您的反馈我已经收到，稍后我将开始调查这个问题。前提分析，智绘教与希沃使用的是不一样的触控库，触控绘制的优先值也是不同的，所以在修复这个问题之前还是建议您在触摸PC设备上使用智绘教的触控功能。稍后给您答复。

**Comment by Alan-CRL** [comment]
> 在使用远程桌面软件(Microsoft Remote Desktop)时。 指针模式下可以正常书写。 但是，触屏模式下滑动只可以看到点状指针（非穿透模式），但无法留下书写痕迹。 同样条件下，最新的希沃(Seewo)白板的全屏书写模式可以工作。
> 
> 远程桌面使用设备：iPad Air 2 智绘教版本：Ver2402.1

@FuziharaYukina 这个问题已经被证实存在，深度分析是触控库的问题，修复起来有难度，修复进度将稍变缓慢， 最后感谢对智绘教的支持！

**Comment by Alan-CRL** [comment]
该问题需要等待 智绘教融合输入模块 制作完成后一并修复

**Comment by Alan-CRL** [comment]
@FuziharaYukina 经过测试，这个问题应该已经得到修复，请下载最新版本尝试，如果一人存在问题，可以要求重新打开此 issues。感谢您对智绘教的支持~
